package com.dspc_explorer.Dtos;
// Generated 07-Feb-2018 08:05:45 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registrar generated by hbm2java
 */
@Entity
@Table(name="registrar"
    ,catalog="dspc_explorer"
)
public class Registrar  implements java.io.Serializable {


     private int regId;
     private Graveowner graveowner;
     private String regFirstName;
     private String regMiddleName;
     private String regLastName;
     private String regSex;
     private String regAge;
     private String regReligion;
     private String regOccupation;
     private String regDeathLocation;
     private String regMarriageStatus;
     private Date regdeathDate;
     private Date regburialDate;

    public Registrar() {
    }

	
    public Registrar(int regId, Graveowner graveowner, String regLastName) {
        this.regId = regId;
        this.graveowner = graveowner;
        this.regLastName = regLastName;
    }
    public Registrar(int regId, Graveowner graveowner, String regFirstName, String regMiddleName, String regLastName, String regSex, String regAge, String regReligion, String regOccupation, String regDeathLocation, String regMarriageStatus, Date regdeathDate, Date regburialDate) {
       this.regId = regId;
       this.graveowner = graveowner;
       this.regFirstName = regFirstName;
       this.regMiddleName = regMiddleName;
       this.regLastName = regLastName;
       this.regSex = regSex;
       this.regAge = regAge;
       this.regReligion = regReligion;
       this.regOccupation = regOccupation;
       this.regDeathLocation = regDeathLocation;
       this.regMarriageStatus = regMarriageStatus;
       this.regdeathDate = regdeathDate;
       this.regburialDate = regburialDate;
    }
   
     @Id 

    
    @Column(name="reg_id", unique=true, nullable=false)
    public int getRegId() {
        return this.regId;
    }
    
    public void setRegId(int regId) {
        this.regId = regId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="graveId", nullable=false)
    public Graveowner getGraveowner() {
        return this.graveowner;
    }
    
    public void setGraveowner(Graveowner graveowner) {
        this.graveowner = graveowner;
    }

    
    @Column(name="reg_first_name", length=100)
    public String getRegFirstName() {
        return this.regFirstName;
    }
    
    public void setRegFirstName(String regFirstName) {
        this.regFirstName = regFirstName;
    }

    
    @Column(name="reg_middle_name", length=100)
    public String getRegMiddleName() {
        return this.regMiddleName;
    }
    
    public void setRegMiddleName(String regMiddleName) {
        this.regMiddleName = regMiddleName;
    }

    
    @Column(name="reg_last_name", nullable=false, length=100)
    public String getRegLastName() {
        return this.regLastName;
    }
    
    public void setRegLastName(String regLastName) {
        this.regLastName = regLastName;
    }

    
    @Column(name="reg_sex", length=100)
    public String getRegSex() {
        return this.regSex;
    }
    
    public void setRegSex(String regSex) {
        this.regSex = regSex;
    }

    
    @Column(name="reg_age", length=100)
    public String getRegAge() {
        return this.regAge;
    }
    
    public void setRegAge(String regAge) {
        this.regAge = regAge;
    }

    
    @Column(name="reg_religion", length=100)
    public String getRegReligion() {
        return this.regReligion;
    }
    
    public void setRegReligion(String regReligion) {
        this.regReligion = regReligion;
    }

    
    @Column(name="reg_occupation", length=100)
    public String getRegOccupation() {
        return this.regOccupation;
    }
    
    public void setRegOccupation(String regOccupation) {
        this.regOccupation = regOccupation;
    }

    
    @Column(name="reg_death_location", length=100)
    public String getRegDeathLocation() {
        return this.regDeathLocation;
    }
    
    public void setRegDeathLocation(String regDeathLocation) {
        this.regDeathLocation = regDeathLocation;
    }

    
    @Column(name="reg_marriage_status", length=100)
    public String getRegMarriageStatus() {
        return this.regMarriageStatus;
    }
    
    public void setRegMarriageStatus(String regMarriageStatus) {
        this.regMarriageStatus = regMarriageStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="regdeath_date", length=10)
    public Date getRegdeathDate() {
        return this.regdeathDate;
    }
    
    public void setRegdeathDate(Date regdeathDate) {
        this.regdeathDate = regdeathDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="regburial_date", length=10)
    public Date getRegburialDate() {
        return this.regburialDate;
    }
    
    public void setRegburialDate(Date regburialDate) {
        this.regburialDate = regburialDate;
    }

    @Override
    public String toString() {
        return "Registrar{" + "regId=" + regId + ", graveowner=" + graveowner + ", regFirstName=" + regFirstName + ", regMiddleName=" + regMiddleName + ", regLastName=" + regLastName + ", regSex=" + regSex + ", regAge=" + regAge + ", regReligion=" + regReligion + ", regOccupation=" + regOccupation + ", regDeathLocation=" + regDeathLocation + ", regMarriageStatus=" + regMarriageStatus + ", regdeathDate=" + regdeathDate + ", regburialDate=" + regburialDate + '}';
    }


    


}


