package com.dspc_explorer.Dtos;
// Generated 07-Feb-2018 08:05:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="dspc_explorer"
)
public class Users  implements java.io.Serializable {


     private Integer userId;
     private int userType;
     private String userName;
     private String userPassword;
     private String passwordSalt;
     private String firstName;
     private String lastName;
     private String email;
     private String mobilePhone;

    public Users() {
    }

	
    public Users(int userType) {
        this.userType = userType;
    }
    public Users(int userType, String userName, String userPassword, String passwordSalt, String firstName, String lastName, String email, String mobilePhone) {
       this.userType = userType;
       this.userName = userName;
       this.userPassword = userPassword;
       this.passwordSalt = passwordSalt;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.mobilePhone = mobilePhone;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="userId", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="userType", nullable=false)
    public int getUserType() {
        return this.userType;
    }
    
    public void setUserType(int userType) {
        this.userType = userType;
    }

    
    @Column(name="userName", length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="userPassword", length=100)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    
    @Column(name="passwordSalt", length=100)
    public String getPasswordSalt() {
        return this.passwordSalt;
    }
    
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    
    @Column(name="firstName", length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastName", length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mobilePhone", length=100)
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }




}


